CREATE TABLE blogz.usertrack
(
  id INT PRIMARY KEY NOT NULL COMMENT 'id' AUTO_INCREMENT,
  userid INT DEFAULT 0 NOT NULL COMMENT '用户id',
  classname VARCHAR(500) COMMENT '操作类名',
  operation VARCHAR(1000) COMMENT '操作',
  url VARCHAR(500),
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  ipadd VARCHAR(100),
  args VARCHAR(500)
);
